### ISSUE TITLE
Store and Manage Roles custom Commands

### ISSUE THREAD

**Issue by Lol3rrr** [Lol3rrr/waswolf#1]
# Current Situation
Right now the Roles that can be selected for a Round are hard-coded in the Bot and can not be updated or customized in any way by the actual Users of the Bot

# Proposal
## New Config Channel
Have the Bot create a custom Channel on the Guild in which it will store the Roles for the Guild

## New Commands
Add custom Commands to add new Roles, remove existing Roles and list all the currently registered Roles.

#### Format:
`/add-role {name} {emoji} {multiple players for the role (true/false/yes/no)} {needs another role assigned to it} {description}`
#### Description
This Command will add a new Role with the given Configuration to the Role set for the Guild. The Bot will need to make sure that some of the Options are unique, like the Name and Emoji used.
This should then also store the new Role in the Config Channel to allow the Bot to load it again the Future

#### Format
`/remove-role {name}`
#### Description
This Command will be used to remove a Role from the Set of Roles for the Guild.
This should then also remove the corresponding Message from the Config Channel.

#### Format
`/list-roles`
#### Description
This Command will simply output a (maybe paged) List of all the Roles and the configuration for each of the Roles

## Update Round starts
The Bot now also needs to load the current Set of Roles when a Round is started. This should be relatively straight forward as all the Roles are stored in the Config Channel

## Implementation Specifics
It would be a good Idea to put a small abstraction (a trait) over the Storage part of this new Feature, as that may allow us to easily add a Database or File storage in the future and not only have the Roles stored in a discord channel.

## TODO
- [ ] Create Custom Channel when needed
- [ ] Serialize and Deserialize Roles to be stored as a Text message
- [ ] Add Roles using a new `/add-role` Command
- [ ] Remove Roles using a new `/remove-role` Command
- [ ] List Roles using a new `/list-roles` Command
- [ ] Load the Roles when a new Round is being started
