### ISSUE TITLE
Add Metrics

### ISSUE THREAD

**Issue by Lol3rrr** [Lol3rrr/waswolf#5]
# Current Situation
Right now the Bot does not collect any sort of Metrics or related information about its current State, which works fine however it would be very useful to at least have the option of tracking certain metrics while it is running as the only other Way to get an idea of what it is doing would be to look through its logs

# Proposal
Add some prometheus Metrics that will be tracked during the lifetime of the Program and expose them through a very simple webserver running alongside the bot itself

# TODOs
- [x] Add boilerplate Metrics stuff
- [x] Add some simple Metrics
- [x] Expose the Metrics using a simple Webserver
