### ISSUE TITLE
Add Info Command

### ISSUE THREAD

**Issue by Lol3rrr** [Lol3rrr/waswolf#7]
# Situation
Right now the Bot just assumes that the User knows about certain Configurations that need to be configured by the User before everything actually works. It will give a hopefully helpful Error Messages when these are not met, however this is still not really a good User Experience overall

# Proposal
Add a simple Info command that displays some general Configuration about the Bot like the Name of the Mod/Game-Master Role and stuff like that, which should hopefully help with understanding everything a bit more

# TODOs
- [ ] Display the Amount of Roles currently configured
- [ ] Display the Name of the Mod/Game-Master Role
- [ ] Display the Name of the Dead Player Role
